FROM nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    python3-opencv \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN python3 -m pip install --upgrade pip setuptools wheel

COPY requirements.txt .
RUN python3 -m pip install -r requirements.txt --find-links .

COPY start_service.py .
COPY src/ ./src/

ENTRYPOINT ["python3", "start_service.py"]